#java -jar ai-service.jar --Spring.profiles.active=dev
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/englishguru"
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: false
logging:
  file: logs/dev/exam_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    guru.springframework.controllers: ERROR
    org.hibernate: ERROR
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
welcome:
  message: Hello
