#java -jar ai-service.jar --Spring.profiles.active=dev
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/englishguru"
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: false
logging:
  file: logs/dev/exam_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    guru.springframework.controllers: ERROR
    org.hibernate: ERROR
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
welcome:
  message: Hello
openai:
  url: "https://api.openai.com/v1/chat/completions"
  ttsUrl: "https://api.openai.com/v1/audio/speech"
  chatgpt:
    models:
      - name: "gpt-4o"
        settings:
          max-tokens: 80       # allows for detailed and lengthy responses
          temperature: 0.8       # balance between creativity and coherence
          top_p: 1.0             # more deterministic responses
          frequency_penalty: 0.0 # no penalty to ensure coherence
          presence_penalty: 0.0  # no penalty to ensure fluid responses
      - name: "gpt-4o-mini"
        settings:
          max-tokens: 100       # for shorter, to-the-point responses
          temperature: 0.6       # more deterministic responses
          top_p: 0.85            # more deterministic and focused responses
          frequency_penalty: 0.2 # to avoid repetition
          presence_penalty: 0.2  # to encourage new content
