#java -jar ai-service.jar --Spring.profiles.active=prod
spring:
  datasource:
    url: "jdbc:postgresql://englishguru.cs9hyeeogxma.eu-west-1.rds.amazonaws.com:5432/englishguru"
    username: postgres
    password: 9616575Ab
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: false
logging:
  file: logs/prod/exam_app.log
  pattern:
    file: "%d %-5level [%thread] %logger{0} : %msg%n"
  level:
    org.springframework.web: ERROR
    guru.springframework.controllers: ERROR
    org.hibernate: ERROR
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
welcome:
  message: Hello
